{% set name = "galore-torch" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/galore-torch-{{ version }}.tar.gz
  sha256: 469f793a0ae1c29cc42d9ba4550fed66983936cb50eccb46b06fbd16cfde40b9
  patches:
    - requirements.patch

build:
  noarch: python
  script: ls && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch
    - transformers
    - bitsandbytes

test:
  imports:
    - galore_torch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jiaweizzhao/GaLore
  summary: 'GaLore: Memory-Efficient LLM Training by Gradient Low-Rank Projection'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
